version: '3.5'
services:

  check-yo-self:
    image: tylertech-scratch-docker-local.jfrog.io/check-yo-self-markgraves:1.0.0
    ports:
      - 5050:8080
    environment:
      - CheckYoSelf__employeesApiBaseUrl=http://check-yo-self-api:8080/
      - CheckYoSelf__employeesButtonVisible=true
    depends_on: 
      - check-yo-self-api

  check-yo-self-api:
    image: tylertech-scratch-docker-local.jfrog.io/check-yo-self-api:1.0.0
    ports:
      - 5051:8080
    environment:
      - CheckYoSelf__IndexerBaseUri=http://check-yo-self-indexer:8080/
      - Data__DatabaseDriver=MySql
      - Data__MySql__ConnectionString=Server=check-yo-self-db;Port=3306;Database=employees;Uid=root;Pwd=checkyoself
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - check-yo-self-indexer

  check-yo-self-indexer:
    image: tylertech-scratch-docker-local.jfrog.io/check-yo-self-indexer:1.0.13
    ports:
      - 5052:8080
    environment: 
      - Elasticsearch__uri=http://elasticsearch:9200
      - Elasticsearch__username=elastic
      - Elasticsearch__password=ElasticAdmin1
      - Elasticsearch__indexName=employees
      - Elasticsearch__maxBulkInsertCount=100
      - Elasticsearch__numberOfReplicas=1
      - Elasticsearch__numberOfShards=5
      - Elasticsearch__useAuthentication=false
      - ASPNETCORE_ENVIRONMENT=Development

  check-yo-self-bootstrapper:
    image: tylertech-scratch-docker-local.jfrog.io/check-yo-self-bootstrapper:1.0.0
    environment: 
      - APICONTAINER=check-yo-self-api:8080
    depends_on: 
      - check-yo-self-api

networks:
  default:
    external:
      name: checkyoself