version: '3.5'
services:

  check-yo-self-db:
    image: mysql:5.7.12
    command: mysqld --innodb-flush-method=fsync
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=checkyoself
      - MYSQL_DATABASE=employees
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DEFAULTS_FILE=/etc/mysql/my.cnf
      - MYSQL_LOG_QUERIES_ENABLED=1

  opensearch:
    image: opensearchproject/opensearch:1
    ports:
      - 9200:9200
      - 9600:9600
    mem_limit: 4g
    environment:
      - ELASTIC_PASSWORD=ElasticAdmin1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  # opensearch-dashboards:
  #   image: opensearchproject/opensearch-dashboards:1
  #   ports:
  #     - 5601:5601
  #   expose:
  #     - "5601"
  #   environment:
  #     - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
  #     - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards

volumes:
  opensearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/opensearch-data
  mysql-data:

networks:
  default:
    name: checkyoself