version: '3.5'
services:

  check-yo-self-db:
    image: mysql:5.7.12
    command: mysqld --innodb-flush-method=fsync
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=checkyoself
      - MYSQL_DATABASE=employees
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DEFAULTS_FILE=/etc/mysql/my.cnf
      - MYSQL_LOG_QUERIES_ENABLED=1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - 9200:9200
    environment:
      - ELASTIC_PASSWORD=ElasticAdmin1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTIC_PASSWORD=ElasticAdmin1

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/elasticsearch-data
  mysql-data:

networks:
  default:
    name: checkyoself